version: '3.8'
services:
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
      MONGO_INITDB_DATABASE: apuestas
  paqueteria:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      MONGO_HOST: mongo-db
      MONGO_PORT: 27017
      MONGO_DB: apuestas
      MONGO_USER: admin
      MONGO_PASS: adminpass


